plugin: amazon.aws.aws_ec2

cache: yes
cache_plugin: ansible.builtin.jsonfile
cache_timeout: 3600
cache_connection: /tmp/aws_inventory
cache_prefix: aws_ec2

aws_profile: snowfork

filters:
  tag:Environment: rococo

hostnames:
  - tag:Name
  - dns-name
  - private-ip-address

strict: False
keyed_groups:
  - key: tags.Role
    prefix: ''
    separator: ''
    parent_group: rococo

compose:
  ansible_host: public_ip_address
