- hosts: relay
  vars:
    channels:
      basic:
        inbound: "0xB6Be7Ab42C75BA987ebC038e4AEC753585b4Ef3b"
        outbound: "0x654dD7719b2D8d57BeBc8B4598AfCf2E5265953b"
      incentivized:
        inbound: "0x0A534A39162aF7Fd031F36e8709f8AE4a0Cd4a68"
        outbound: "0x4a838cD37220bCf2dD278e9B31F8B3e3DE3a9550"
    endpoints:
      ethereum: wss://ropsten.infura.io/ws/v3/e8b4790b8e4049cca3c04f738cfa25f2
      substrate: wss://parachain-rpc.snowfork.network
  vars_files:
    - vars/keys.yml

  tasks:
    - name: Basic preparation
      import_tasks: tasks/base.yml

    - name: Create config dir
      file:
        path: /etc/artemis-relay
        state: directory

    - name: Download artifacts
      amazon.aws.aws_s3:
        bucket: snowfork-rococo
        object: "{{ item.object }}"
        dest: "{{ item.dest }}"
        mode: get
      loop:
        - object: artemis-relay
          dest: /usr/local/bin/artemis-relay
        - object: subkey
          dest: /usr/local/bin/subkey

    - name: Make binaries executable
      file:
        path: "{{ item }}"
        mode: 0755
      loop:
        - /usr/local/bin/artemis-relay
        - /usr/local/bin/subkey

    - name: Generate configuration
      template:
        src: relay-config.toml.j2
        dest: /etc/artemis-relay/config.toml
        owner: root
        group: root
        mode: 0644
      notify: Restart relay

    - name: Create service file
      template:
        src: relay.service.j2
        dest: /etc/systemd/system/artemis-relay.service
        owner: root
        group: root
        mode: 0644
      notify: Restart relay

    - name: Enable relay service
      systemd:
        name: artemis-relay
        state: started
        enabled: yes

  handlers:
    - name: Restart relay
      systemd:
        name: artemis-relay
        state: restarted
        daemon_reload: yes
