- hosts: parachain-node-0
  vars:
    rpc_dns_name: parachain-rpc.snowfork.network

  tasks:
    - name: Create nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
