[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/bridge',
    'pallets/broker',
    'pallets/dummy-verifier',
    'pallets/dummy-app',
    'runtime',
    'common'
]
