[profile.release]
panic = 'unwind'

[workspace]
members = [
    'ethereum/eth-signature',
    'node',
    'pallets/bridge',
    'pallets/broker',
    'pallets/dummy-verifier',
    'pallets/polkaeth-app',
    'runtime',
    'common'
]
