[profile.release]
panic = 'unwind'

[workspace]
members = [
    'primitives/core',
    'primitives/ethereum',
    'pallets/bridge',
    'pallets/broker',
    'pallets/asset',
    'pallets/dummy-verifier',
    'pallets/polkaeth-app',
    'pallets/polkaerc20-app',
    'node',
    'runtime',
]

